### ISSUE TITLE
To-do [Week 3]

### ISSUE THREAD

**Issue by jlaurentpdx** [jlaurentpdx/beginning-maker-tech#1]
- [x] ~~Update Week 2 course content~~
- [x] ~~Week 1 features a broken link to an image file - Anatomy of an Arduino UNO now exists in /img~~
- [x] ~~Add resources page~~
- [x] ~~Relocate Week 1 materials to Resources~~
- [x] Relocate Week 2 materials for Resources 
- [x] Add overview of Week 2 Coding lecture 
- [x] Add Week 3 material 
- [x] Fix jlaurentpdx.github.io Logo
